module.exports = {
    workspace: process.env[(process.platform === 'win32') ? 'USERPROFILE' : 'HOME'] + '/cdjs-agent-1',

    wsEvents: {
        BUILD_STATUS: 'BUILD_STATUS',
        LOG: 'LOG',
        SEND_MESSAGE_TO_AGENT: 'SEND_MESSAGE_TO_AGENT',
        CREATE_AGENT_COMMUNICATION_TUNNEL: 'CREATE_AGENT_COMMUNICATION_TUNNEL',
        CREATE_AGENT_COMMUNICATION_TUNNEL_RESPONSE: 'CREATE_AGENT_COMMUNICATION_TUNNEL_RESPONSE',
        MESSAGE_FROM_AGENT: 'MESSAGE_FROM_AGENT'
    },

    agentMessages: {
        PREPARE_DIR: 'PREPARE_DIR',
        PREPARE_DIR_COMPLETE: 'PREPARE_DIR_COMPLETE',
        CLONE: 'CLONE',
        CLONE_COMPLETE: 'CLONE_COMPLETE',
        CHECK_OUT: 'CHECK_OUT',
        CHECK_OUT_COMPLETE: 'CHECK_OUT_COMPLETE',
        NPM_INSTALL: 'NPM_INSTALL',
        NPM_INSTALL_COMPLETE: 'NPM_INSTALL_COMPLETE',
        RUN_SCRIPT: 'RUN_SCRIPT',
        RUN_SCRIPT_COMPLETE: 'RUN_SCRIPT_COMPLETE',
        SAVE_BUILD: 'SAVE_BUILD',
        DONE: 'DONE',
        ERROR: 'ERROR',
        LOG: 'LOG',
    }
};